### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by minh-dai** [Ashwin-Mothilal/react-native-secure-window#3]

**Comment by Ashwin-Mothilal** [comment]
Can you add what is the error you're facing, or please share a sample project?

**Comment by minh-dai** [comment]
I added your library, in the my iPhone don't have any error and it don't working

**Comment by Ashwin-Mothilal** [comment]
This library currently supports Android only. There is no official way to secure screen in iOS. Any hacky PR's are welcome.
