### ISSUE TITLE
Android doesn't show a blurred screen

### ISSUE THREAD

**Issue by apfz** [Ashwin-Mothilal/react-native-secure-window#8]
Is it correct that Android does not show a blurred screen as is the case with iOS?

I have tried for example to run it on a Pixel 6, with Android 13 (API level 33), but only the screenshot is disabled, no blurred screen visible.

**Comment by Ashwin-Mothilal** [comment]
Yes it's correct. Because Android has native feature to disable screenshots, screen recording, casting but iOS doesn't. So, it's hidden with a blur view.
